org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

project_name=kami-mods

mod_authors=kami-tsuki
mod_license=All Rights Reserved
mod_group=kami

java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.251
neo_version_range=[21.1,)
kff_version=5.12.0

create_version_range=[6.0.10,)
numismatics_version_range=[1.0,)

deploy_enabled=true

# Test server instance
deploy_server_dir=Test-Server-NeoForge-1.21.1

# Test Client instance
deploy_instance_dir=E:/MC_Prism/Instances/1.21.1/minecraft
