package kami.geology.config

object Docs {
    val general = mapOf(
        "dimensions" to "Dimensions that get deposits.",
        "removeOriginalOres" to "Remove other worldgen that places the ores defined in ores/.",
        "disableOreVeins" to "Turn off the vanilla noise-based iron and copper veins (raw ore blocks in tuff and granite).",
        "discoverOres" to "Generate an ore file for every overworld ore block tagged c:ores that no file in ores/ covers yet, so modded ores are picked up. Delete or disable a generated file to keep it out.",
        "fallbackProvince" to "Province for biomes no province lists, such as modded biomes. Remove for none.",
        "removeFeatures" to "Extra placed features to remove.",
        "keepFeatures" to "Placed features that are never removed.",
        "replaceable" to "Blocks that ores may replace.",
        "deepslateHosts" to "Blocks that get the deepslate ore.",
        "siteCache" to "Deposit sites kept in memory.",
        "auditThreshold" to "Ore blocks an area needs to count as having a supply, used by the audit command.",
        "chains" to "Production chains checked by the audit command: name to the ores it needs.",
        "richness" to "Deposit grades: drop and ore density multipliers.",
        "richness.grades.weight" to "Relative chance of a grade."
    )

    val ore = mapOf(
        "enabled" to "Turn this ore off without deleting the file.",
        "blocks.stone" to "Ore block in normal rock.",
        "blocks.deepslate" to "Ore block in deepslate.",
        "blocks.hosts" to "Ore block for a specific host rock.",
        "blocks.strip" to "More ore blocks whose worldgen is removed. Blocks tagged c:ores/<file name> are always included.",
        "provinces" to "Chance multiplier per province, 0 to 1.",
        "deposit" to "Large deposits on a jittered grid. Remove to disable.",
        "deposit.shape.kind" to "sheet, seam, band, pipe, pods or cloud.",
        "deposit.shape.dip" to "Tilt in degrees, min and max.",
        "deposit.shape.warp" to "Edge irregularity.",
        "deposit.shape.warpScale" to "Size of the irregularity in blocks.",
        "deposit.shape.layers" to "Seam only: stacked layers.",
        "deposit.shape.bandWidth" to "Band only: layer thickness in blocks.",
        "deposit.shape.bandCut" to "Band only: -1 to 1, higher means thinner bands.",
        "deposit.shape.taper" to "Pipe only: narrowing towards the bottom, 0 to 1.",
        "deposit.shape.lean" to "Pipe only: sideways tilt.",
        "deposit.shape.lumps" to "Pods only: pod count, min and max.",
        "deposit.shape.cut" to "Cloud only: -1 to 1, higher means sparser.",
        "deposit.spacing" to "Grid cell size in blocks.",
        "deposit.chance" to "Chance per grid cell, before province weights.",
        "deposit.height" to "Center height, min and max.",
        "deposit.minDepth" to "Blocks a deposit must sit below the surface.",
        "deposit.density" to "Chance that a body block becomes ore.",
        "deposit.bodyRadius" to "Where the sparse fringe starts, 0 to 1.",
        "deposit.fringe" to "Ore chance at the very edge, 0 to 1.",
        "deposit.airDiscard" to "Chance to drop ore that touches air.",
        "deposit.tiers" to "Size classes, lengths in blocks as min and max.",
        "deposit.minSurface" to "Only place where the terrain surface is at least this high, for mountain-only ores.",
        "deposit.surfaceDepth" to "Pick the height as blocks below the surface, min and max, then clamp to deposit.height.",
        "deposit.limit" to "Hard vertical limit of the ore body, min and max Y. Remove for none.",
        "deposit.anchor" to "Place next to another ore's deposits instead of on the grid.",
        "deposit.anchor.tiers" to "Tiers of the other ore that qualify, empty for all.",
        "deposit.anchor.chance" to "Chance per qualifying deposit.",
        "deposit.anchor.absoluteY" to "Pick the height from deposit.height instead of offsetting from the other deposit.",
        "deposit.anchor.offsetX" to "Offset from the other deposit center.",
        "scatter" to "Small background veins. Remove to disable.",
        "scatter.perChunk" to "Average veins per chunk.",
        "scatter.size" to "Vein size in blocks, min and max.",
        "scatter.height" to "Height range, min and max.",
        "scatter.distribution" to "uniform or triangle.",
        "scatter.airDiscard" to "Chance to drop ore that touches air.",
        "scatter.provinces" to "Restrict to provinces, remove for anywhere.",
        "core.chance" to "Chance that a deposit has a dense core.",
        "core.block" to "Core block.",
        "core.radius" to "Core size relative to the deposit.",
        "core.airDiscard" to "Chance to drop core blocks that touch air.",
        "halo.blocks" to "Rock that replaces the host around the deposit.",
        "halo.scale" to "Halo size relative to the deposit, above 1.",
        "halo.density" to "Chance that a halo block is replaced.",
        "halo.replace" to "Blocks the halo may replace, remove for the general list.",
        "outcrop.blocks" to "Surface blocks above shallow deposits.",
        "outcrop.maxDepth" to "Deepest deposit that still shows on the surface.",
        "outcrop.density" to "Chance per surface block.",
        "outcrop.oreShare" to "Share of outcrop blocks that are the ore itself.",
        "outcrop.replace" to "Surface blocks that may be replaced."
    )
}
