name: KamiEconomy

on:
  push:
    branches: [main, master, develop, 'release**']
    paths:
      - 'KamiEconomy/**'
      - 'KamiLibs/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - '.github/workflows/_mod-ci.yml'
      - '.github/workflows/KamiEconomy.yml'

jobs:
  ci:
    uses: ./.github/workflows/_mod-ci.yml
    with:
      mod: KamiEconomy
